### ISSUE TITLE
When Python client?

### ISSUE THREAD

**Issue by dsmurrell** [apioo/typeapi#2]
^ :)

**Comment by chriskapp** [comment]
Hey @dsmurrell, we have currently some clients on our roadmap like C#, Kotlin, Python, Rust and Swift, if others are also interested in Python please let us know with a like, then we will consider this for our roadmap

**Comment by dsmurrell** [comment]
Ok, awesome. Thank you!

**Comment by madhavajay** [comment]
+1 for Python

**Comment by chriskapp** [comment]
@dsmurrell @madhavajay just FYI we have finally released a Python client using [pydantic](https://docs.pydantic.dev/latest/), you can also get a first preview directly at our generator s. https://typeapi.org/generator
